# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2019-2020 Maximilian Luz <luzmaximilian@gmail.com>

obj-$(CONFIG_SURFACE_AGGREGATOR_DEBUGFS)	+= surface_aggregator_debugfs.o
obj-$(CONFIG_SURFACE_ACPI_NOTIFY)		+= surface_acpi_notify.o
